general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    path = ~/Pictures/wallpapers/ufo_and_cat.png

}

animation {
    enabled = true
}

input-field {
    size = 100, 100
    hide_input = true
    outline_thickness = 5
    font_color = rgba(201, 43, 16, 1.0)
    inner_color = rgba(0, 0, 0, 1.0)
    outer_color = rgba(35, 237, 55, 1.0)
}

label {
    text = $TIME
    font_size = 96
    position = 0, 280
    
}
